name: Python CI/CD

on:
  push:
    branches: [ main, staging ]

env:
  PYTHON_VERSION: '3.12.3'
  APP_DIR: ${{ vars.APP_DIR }}
  STAGING_APP_DIR: ${{ vars.APP_DIR }}-staging
  VENV_NAME: ${{ vars.VENV_NAME }}
  STAGING_VENV_NAME: ${{ vars.VENV_NAME }}-staging
  SERVICE_NAME: ${{ vars.SERVICE_NAME }}
  STAGING_SERVICE_NAME: ${{ vars.STAGING_SERVICE_NAME }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
  deploy-production:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install rsync (for file transfer)
      run: sudo apt-get update && sudo apt-get install -y rsync
    
    - name: Deploy to Production
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          set -euo pipefail
          echo "🚀 Starting Python PRODUCTION deployment..."
          
          # Clone or update the repository
          if [ ! -d "${{ env.APP_DIR }}" ]; then
            git clone https://github.com/${{ github.repository }}.git ${{ env.APP_DIR }}
          else
            cd ${{ env.APP_DIR }}
            git fetch origin main
            git reset --hard origin/main
          fi
          
          # Navigate to app directory
          cd ${{ env.APP_DIR }}
          
          # Create virtualenv if not exists
          if [ ! -d "${{ env.VENV_NAME }}" ]; then
            python3 -m venv ${{ env.VENV_NAME }}
          fi
          
          # Activate virtualenv
          source ${{ env.VENV_NAME }}/bin/activate
          
          # Install dependencies
          pip install --upgrade pip
          pip install -r requirements.txt
          
          # Check if service exists before restarting
          if systemctl list-unit-files | grep -q "^${{ env.SERVICE_NAME }}"; then
            echo "🔄 Restarting production service..."
            sudo systemctl restart ${{ env.SERVICE_NAME }}
          else
            echo "❌ Production service not found: ${{ env.SERVICE_NAME }}"
            exit 1
          fi
          
          echo "✅ PRODUCTION deployment successful!"

  deploy-staging:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install rsync (for file transfer)
      run: sudo apt-get update && sudo apt-get install -y rsync
    
    - name: Deploy to Staging
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          set -euo pipefail
          echo "🚀 Starting Python STAGING deployment..."
          
          # Clone or update the repository
          if [ ! -d "${{ env.STAGING_APP_DIR }}" ]; then
            git clone https://github.com/${{ github.repository }}.git ${{ env.STAGING_APP_DIR }}
          else
            cd ${{ env.STAGING_APP_DIR }}
            git fetch origin staging
            git reset --hard origin/staging
          fi
          
          # Navigate to app directory
          cd ${{ env.STAGING_APP_DIR }}
          
          # Create virtualenv if not exists
          if [ ! -d "${{ env.STAGING_VENV_NAME }}" ]; then
            python3 -m venv ${{ env.STAGING_VENV_NAME }}
          fi
          
          # Activate virtualenv
          source ${{ env.STAGING_VENV_NAME }}/bin/activate
          
          # Install dependencies
          pip install --upgrade pip
          pip install -r requirements.txt
          
          # Check if service exists before restarting
          if systemctl list-unit-files | grep -q "^${{ env.STAGING_SERVICE_NAME }}"; then
            echo "🔄 Restarting staging service..."
            sudo systemctl restart ${{ env.STAGING_SERVICE_NAME }}
          else
            echo "❌ Staging service not found: ${{ env.STAGING_SERVICE_NAME }}"
            exit 1
          fi
          
          echo "✅ STAGING deployment successful!"
